services:
  - type: web
    name: society-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromDatabase:
          name: societyhub
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: societyhub
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: societyhub
          property: password
      - key: APP_FRONTEND_URL
        fromService:
          name: society-admin-web
          type: web
          property: url
      - key: JWT_COOKIE_SECURE
        value: "true"

  - type: web
    name: society-admin-web
    env: static
    rootDir: admin-web
    plan: free
    buildCommand: npm ci ; npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: society-backend
          type: web
          property: url

databases:
  - name: societyhub-db 
    databaseName: societyhub
    user: society_user