services:
  - type: web
    name: society-backend
    env: java
    rootDir: backend
    plan: free
    buildCommand: chmod +x mvnw ; ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health

  - type: web
    name: societyhub-webapp
    env: static
    rootDir: frontend
    plan: free
    buildCommand: npm ci ; npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: society-db
    databaseName: society_db
    user: society_user
