CREATE TABLE IF NOT EXISTS society_settings (
    id BIGSERIAL PRIMARY KEY,
    society_id BIGINT NOT NULL UNIQUE REFERENCES societies(id) ON DELETE CASCADE,
    maintenance_rate_per_sqft NUMERIC(12,2) NOT NULL DEFAULT 0,
    water_charges_fixed NUMERIC(12,2) NOT NULL DEFAULT 0,
    water_charges_per_person NUMERIC(12,2) NOT NULL DEFAULT 0,
    sinking_fund_per_sqft NUMERIC(12,2) NOT NULL DEFAULT 0,
    repair_fund_per_sqft NUMERIC(12,2) NOT NULL DEFAULT 0,
    parking_charge_open NUMERIC(12,2) NOT NULL DEFAULT 0,
    parking_charge_covered NUMERIC(12,2) NOT NULL DEFAULT 0,
    parking_charge_stilt NUMERIC(12,2) NOT NULL DEFAULT 0,
    parking_charge_two_wheeler NUMERIC(12,2) NOT NULL DEFAULT 0,
    lift_maintenance_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
    electricity_common_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
    security_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
    insurance_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
    club_house_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
    property_tax_share NUMERIC(12,2) NOT NULL DEFAULT 0,
    non_occupancy_surcharge_pct NUMERIC(5,2) NOT NULL DEFAULT 0,
    gst_percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
    late_payment_interest_pct NUMERIC(5,2) NOT NULL DEFAULT 0,
    grace_period_days INTEGER NOT NULL DEFAULT 5,
    penalty_fixed NUMERIC(12,2) NOT NULL DEFAULT 0,
    bill_generation_day INTEGER NOT NULL DEFAULT 1,
    due_date_day INTEGER NOT NULL DEFAULT 10,
    financial_year_start_month INTEGER NOT NULL DEFAULT 4,
    bill_number_prefix VARCHAR(20) NOT NULL DEFAULT 'BILL',
    receipt_number_prefix VARCHAR(20) NOT NULL DEFAULT 'RCT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_society_settings_society_id ON society_settings(society_id);